### ISSUE TITLE
Error on Anki 2.1.45

### ISSUE THREAD

**Issue by marreromarco** [BlueGreenMagick/Review-Hotmouse#13]
It seems that the add-on is not working on the latest Anki 2.1.45

![2021-08-02_00-18](https://user-images.githubusercontent.com/58692066/127803853-0839488b-4782-4257-85dc-f85fe18113e2.png)

Would it be possible to provide support for the latest Anki version ?

**Comment by comcaptain** [comment]
I got the same issue with Anki 2.1.45. But the behavior is a bit different:
- This error always appear when I start up Anki
- But despite this error, most of the time this plugin still works. And even if sometimes it does not work, restarting anki would fix the issue

**Comment by BlueGreenMagick** [comment]
Updated the add-on! The new version works on the latest Anki v2.1.47.
