### ISSUE TITLE
The configurations are reversed on switching deck

### ISSUE THREAD

**Issue by QueenEvanescence** [BlueGreenMagick/Review-Hotmouse#14]
hi  so i recently downloaded this and I LOVE IT!
but whenever i shift from one deck to another the configurations reverse
For example if scroll down was the original show ans
when i switch decks scroll down shows up as q_wheel_up and on scrolling up it shows as show_ans
same for the good command 
so basically in the second deck instead of scrolling down i need to scroll up to see answer and mark as good

**Comment by BlueGreenMagick** [comment]
That's a serious issue 😱 Fixed and updated just now!

The reason was Qt and web had different thoughts on whether scroll up should be positive value or negative. Thankfully, it should have been quite rare to encounter the issue.

**Comment by QueenEvanescence** [comment]
oh wow that was fast! 
I tried it out and it works perfectly! 
THANK YOU!
