### ISSUE TITLE
Question Hotkeys 

### ISSUE THREAD

**Issue by hanjami** [BlueGreenMagick/Review-Hotmouse#16]
Hello, I'm greatly enjoying your add-on! 
Is it possible to add shortcuts for answer buttons in the 'Question Hotkeys'? Sometimes I like to use those buttons without checking the answer, so I tried to configure in advanced, but it showed an error message saying that buttons like 'again' are "not in list". 
Thank you.

**Comment by BlueGreenMagick** [comment]
Added! Though keep in mind that while it works on atleast 2.1.49 ~ 2.1.52, it might have problems in future Anki versions. Please create an issue if you encounter one.
