### ISSUE TITLE
New Update Right Click

### ISSUE THREAD

**Issue by alecsdough** [BlueGreenMagick/Review-Hotmouse#25]
Hello,

I downloaded the new update today and it's causing the right click to show the dropdown menu with "Copy" on it. This wasn't present before the update and it's really slowing down my hotmouse actions, especially when I want to scroll and undo cards. If this was an intended feature and you won't be fixing it, is there any way you could add a downgrade feature in order to go back to the previous version please? Thank you for the addon and for your time.

**Comment by BlueGreenMagick** [comment]
Thanks for the report! Should be fixed in the new update
