### ISSUE TITLE
Manual turn off option

### ISSUE THREAD

**Issue by ghost** [BlueGreenMagick/Review-Hotmouse#3]
Hello.
Some trackpads cannot click right when the left is pressed so it is quite hard for me to disable hotmouse in reviewer when not using an external mouse.
A disable/enable button in the tools or study column in the menu bar would be appreciated.
Thank you.

**Comment by BlueGreenMagick** [comment]
Sorry for the inconvenience! I hadn't realized such use cases. Currently, you can change the the actions you need to take to disable hotmouse, in the config. But I'll consider adding a button somewhere - though can't promise it'll happen anytime soon.

**Comment by Cupbox** [comment]
No problem. Please take your time.

**Comment by BlueGreenMagick** [comment]
Added in the tools menu!
