### ISSUE TITLE
Changing profiles creates error message

### ISSUE THREAD

**Issue by amazeum** [BlueGreenMagick/Review-Hotmouse#4]
Hi there,

An error message is generated after I open the browse window in a profile and then switch profiles and open a new browse window. I isolated the problem to this add-on and attached the error report. Thanks in advance for taking a look at this!

[Anki Error Report - HotMouse.txt](https://github.com/BlueGreenMagick/Review-Hotmouse/files/4398107/Anki.Error.Report.-.HotMouse.txt)

**Comment by amazeum** [comment]
I took a closer look at the code and think it may have to do with lines 205-208. I have essentially no experience coding in Python but to me it seems to be a hook incompatibility due to the rapidly evolving Anki hooks. I commented out those lines, which resolved the error message, but it unfortunately removed useful functionality (performing multiple click actions on the review screen, although single clicks still worked).

**Comment by BlueGreenMagick** [comment]
Thanks for the detailed issue report! I fixed the bug, although I still can't figure out why it causes an error in the first place. Should be fixed in the next update.

**Comment by BlueGreenMagick** [comment]
(Note to future self) Regarding the issue, this is what I found

```
from aqt.webview import AnkiWebView
from aqt.utils import showText
from anki.hooks import wrap

def on_child_event(self, event, x="abc", y="def", _old=lambda s,e: None):
     return None

def on_child_event2(*args, _old, **kwargs):
    showText(str(args))
    return _old(*args, **kwargs)

AnkiWebView.childEvent = on_child_event
AnkiWebView.childEvent = wrap(AnkiWebView.childEvent, on_child_event2, "around")

# I expect showText to output (AnkiWebView, QChildEvent)
# But it actually outputs (AnkiWebView, QChildEvent, "abc", "def", lambda s,e: None)
# You can test this by running this script in the debug console, then going to the card browser afterwards
# Tested on Anki 2.1.22, Python 3.8.1, Qt 5.14.1
#
# documentation on childEvent
# https://doc.qt.io/qt-5/qobject.html#childEvent
#
#  void QObject::childEvent(QChildEvent *event)
#
```
I really can't figure out how default arguments of parameters that don't get used, could be inputted in its wrapper function as arguments.

Could I possibly ask for your input, @Arthur-Milchior, @glutanimate? You're the only only ones I can think of who knows Anki code and Python much better than me.

**Comment by Arthur-Milchior** [comment]
I don't understand why you ask our help. Seems you solved it yourself with https://github.com/BlueGreenMagick/Review-Hotmouse/commit/765cfcc5a08ca15c22219f664989c9b8de66f0b9
You simply want to wrap the method a single time. Using profile loader hook wrap twice.
I never really paid attention to the fact that wrapping twice the same method with around is dangerous. But it makes sens that,doing so ensure that _old is a variable given both to the first wrapping and to the second wrapping. So there are actually two variables name _old in the second wrapping, one directly named _old and one in **kwargs. Which creates this error. And I see no way to correct it in anki without just breaking wrapping.

**Comment by BlueGreenMagick** [comment]
Sorry, I didn't realize that `decorator.decorator` used in `wrap` wasn't a normal decorator, but preserves the function signatures. So the new function is called with the default arguments from the old function.
Thanks for the help!
