### ISSUE TITLE
Actions functioning outside of reviewer

### ISSUE THREAD

**Issue by lostasock** [BlueGreenMagick/Review-Hotmouse#6]
1. From Anki deck screen, open deck and start reviewing.
2. From reviewer, open browser.
3. Focus mouse on edit field part (scrollable, due to large amount of fields) Seemingly only the edit field part, other parts of the browser seem to behave normally.
4. Mouse wheel scroll actions from mouse are still functioning (browser has focus, mouse behaves both as normal inside browser AND reviews cards).

other info:
Review screen does not change to "Wait for editing to finish" until a field is selected in the browser, but you are able to scroll the browser without the reviewer saying "wait for editing to finish" - causing the issue described above.

I disabled all addons except review hotmouse and it still functions as above.

Same behaviour for some other windows. I checked note edit window, and MIA Dictionary addon.

Anki Version 2.1.22 (0ecc189a)
Latest version of review hotmouse (whatever is on ankiweb as of today, v1.3?)

Hope this is enough info to get you started.

**Comment by BlueGreenMagick** [comment]
Thanks for the bug report, was a quite interesting one. It was fixed in the latest update.

**Comment by lostasock** [comment]
Just checked it, all working. Thanks!
