### ISSUE TITLE
suggestion for on/off

### ISSUE THREAD

**Issue by Laern2Do** [BlueGreenMagick/Review-Hotmouse#7]
hey there, 

first off, i really really like this add-on so thx you for creating this!

is it possible to have the option off/on assign to a single click-button. 
Example:
1. first click - off,
2. click again- on,

currently after turning it off, i have to right-click to open a context menu to re-enable the function

(i wonder if this a mouse issue, right-click context menu issue or anki issue, but i cant "scroll" to select options after right click to open the context-menu, not a big deal but if this enhancement option is possible i like to drop the suggestion here as well) 

Thx!

version 2.1.22, window 10

**Comment by Cashburner** [comment]
very good suggestion, has anyone fount the config option for on?

**Comment by BlueGreenMagick** [comment]
There isn't one currently. But there are a lot of people requesting an 'on' button so I'll be adding them in the next update.

**Comment by Laern2Do** [comment]
Nice! Would it possible to assign on/off on the same button? Or 2 different buttons for the on/off functions? (I prefer the first one xD, and hopefully for 2.1.26 haha)...

Thank you so much for looking into this, im looking forward to it :)

**Comment by BlueGreenMagick** [comment]
Updated! The new version (which requires Anki v2.1.27+) has an action `on_off`.
