### ISSUE TITLE
double scrolling

### ISSUE THREAD

**Issue by khonkhortisan** [BlueGreenMagick/Review-Hotmouse#8]
I'll copy what I wrote as I was troubleshooting this:

---

accidentally flipping to answer side: This time I have proof: I pressed s to start studying, scrolled down to get to the answer side, left clicked to divide the log, scrolled down to answer good and get to the next card, and it went to the answer side as if I scrolled down twice, but the log shows I only scrolled once.
![imagen](https://user-images.githubusercontent.com/1996449/88134043-782e7700-cb98-11ea-8fa8-7f91589b4237.png)
It's either review hotmouse by itself or an interaction with another addon modifying the same function, I don't think it has ever done that when I use the keyboard.
![imagen](https://user-images.githubusercontent.com/1996449/88134067-87adc000-cb98-11ea-8bc0-94bd4048c8d5.png)
My config matched the default. With "tooltip": true, "z_debug": true, starting from the answer side of a card, scrolling down once (verified with the ahk log), in a tooltip it'll say [good] and show the next card then almost immediately say [show_ans] and show the answer. This gives a hint to where in the code the command is getting duplicated.
![imagen](https://user-images.githubusercontent.com/1996449/88134084-93998200-cb98-11ea-9f86-0c4549c1b005.png)
![imagen](https://user-images.githubusercontent.com/1996449/88134092-998f6300-cb98-11ea-9bbb-f5b72cc9b576.png)
![imagen](https://user-images.githubusercontent.com/1996449/88134101-9e541700-cb98-11ea-8ae3-2c58864509cb.png)
![imagen](https://user-images.githubusercontent.com/1996449/88134112-a3b16180-cb98-11ea-9765-6a8b89acf215.png)
oh it's literally registering two mouse wheel handlers. Potentially bypassing its own double-click check timeout?
not sure whether to disable setting AnkiWebView.wheelEvent (if the other event always fires), or to set ignore_release = True (to handle it right assuming both event types are needed). Went with the first one. It'll either fail to scroll sometimes or work perfectly now.
I'm guessing it goes like this: on the answer side, event_filter, grade it good, load the next card for more than 350ms, on_scroll, it gets counted as a second scroll because it's more than threshold_wheel_ms, show the answer side.
DavidA: Stick some logging in and find out?
correct behavior: click, scroll (event_filter), show answer
![imagen](https://user-images.githubusercontent.com/1996449/88134157-bf1c6c80-cb98-11ea-87d4-4503c795ef12.png)
incorrect behavior: scroll (event_filter), rate good, (on_wheel), show answer
![imagen](https://user-images.githubusercontent.com/1996449/88134175-c5aae400-cb98-11ea-88d3-7493d0b2f6ec.png)
I had the event order right (event_filter before on_scroll), let me add timestamps
![imagen](https://user-images.githubusercontent.com/1996449/88134193-cf344c00-cb98-11ea-978b-f4714b9bbe01.png)
![imagen](https://user-images.githubusercontent.com/1996449/88134202-d4919680-cb98-11ea-8168-dda823a1914b.png)
0.0799871 to 0.0889965 seconds makes it not do the second action, 0.6399715 to 0.697945 seconds makes it do the second action. I'm subtracting the event_filter→on_mouse_press timestamp, which is slightly delayed from when event_filter is called, from the on_wheel timestamp. Consistent with the 350ms (0.350 seconds) threshold.

---

For reproducibility, my copy of the file where I added print statements:
[__init__.py.txt](https://github.com/BlueGreenMagick/Review-Hotmouse/files/4957830/__init__.py.txt)

I'm on Anki 2.1.28. To reach the threshold, you can slow down your computer filling up the memory, or maybe by putting a lot on the card (assuming it calls event_filter, then loads the card, then calls on_wheel). The specific anki version may or may not matter for whether on_wheel gets called.
[CopyDebugInfo.txt](https://github.com/BlueGreenMagick/Review-Hotmouse/files/4957846/CopyDebugInfo.txt)

**Comment by BlueGreenMagick** [comment]
Thanks! 0486d55 removing on_wheel should fix the issue.
